# Generated by Django 4.2.2 on 2023-10-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_phonenumber', models.IntegerField(unique=True)),
                ('otp_datetime', models.DateTimeField()),
                ('otp_value', models.IntegerField()),
            ],
        ),
    ]
