# Generated by Django 4.2.2 on 2023-10-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_phonenumber',
            new_name='phonenumber',
        ),
    ]
