# Generated by Django 4.2.2 on 2023-10-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_otp_phonenumber_otp_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_value',
            field=models.IntegerField(null=True),
        ),
    ]
