# Generated by Django 4.2.2 on 2023-06-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_manufacturer_musicalinstrument_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='musicalinstrument',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='musicalinstrument',
            name='instrument_desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
