version: '3'
services:
  db:
    image: postgres
    environment:
      ENGINE: django.db.backends.postgresql
      DB_NAME: MusicStore
      DB_USER: postgres
      DB_PASSWORD: p0stgr3
      DB_HOST: localhost
      DB_PORT: 5432
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      SECRET_KEY: django-insecure-8lgy&nxxuhn8yyx+ct60pv&te8vwjwj(irxepund++v+602u6&
      STRIPE_PUBLISHABLE_KEY: pk_test_51NNKyPLkcNvm45Uvp7a6rzwbKgEtKddkTMM8CxuFC9eLlrQ4M3YmWBhmhnUuFK5s7ukEXSA0Qqd7ofLAlHFAjJSg00IkLnQmzV
      STRIPE_SECRET_KEY: sk_test_51NNKyPLkcNvm45Uv6GS2K1LJqV0LveQaSWLEr8AxYql9A7PM3yVVr5n7kXZAFlZDc0LYeDCwF2BOCKqXQ6CngNaE000CllRsCJ
      BACKEND_DOMAIN: http://127.0.0.1:8000
      PAYMENT_SUCCESS_URL: http://127.0.0.1:8000/success/
      PAYMENT_CANCEL_URL: http://127.0.0.1:8000/cancel/
    volumes:
      - .:/code
    depends_on:
      - db

  web_migrate:
    extends:
      service: web
    command: python manage.py createsuperuser && python manage.py migrate

  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      -  "8000:8000"
