# Generated by Django 4.2.2 on 2023-06-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalinstrument',
            name='instrument_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
