# Generated by Django 4.2.2 on 2023-06-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalinstrument',
            name='instrument_desc',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
