# Generated by Django 4.2.2 on 2023-10-22 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CoachContracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Website', 'Website')], max_length=100)),
                ('profile_url', models.TextField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_experience', models.IntegerField(null=True)),
                ('coach_about_education', models.TextField(blank=True, max_length=300, null=True)),
                ('coach_about_athletic', models.TextField(blank=True, max_length=300, null=True)),
                ('coach_about_communities', models.TextField(blank=True, max_length=300, null=True)),
                ('coach_address', models.TextField(blank=True, max_length=300, null=True)),
                ('coach_city', models.TextField(max_length=100)),
                ('coach_county', models.TextField(max_length=100)),
                ('coach_socialmedia', models.ManyToManyField(related_name='coach_socialmedia', to='coaching.coachsocialmedia')),
                ('coach_speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoachContracts.expertise')),
                ('coach_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
