# Generated by Django 4.2.2 on 2023-10-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_county',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
