# Generated by Django 4.2.2 on 2023-10-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_coach_coach_gender_coach_coach_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_rating',
            field=models.FloatField(default=0),
        ),
    ]
