# Generated by Django 4.2.2 on 2023-10-22 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_code', models.IntegerField(null=True)),
                ('captcha_date', models.DateTimeField()),
                ('captcha_img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='coach_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_sharecode', models.CharField(max_length=100, null=True)),
                ('coach_city', models.CharField(max_length=50, null=True)),
                ('coach_experience', models.IntegerField(null=True)),
                ('coach_specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoachContracts.expertise')),
                ('coach_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
