# Generated by Django 4.2.2 on 2023-10-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoachContracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach_requests',
            name='coach_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
