# Generated by Django 4.2.2 on 2023-10-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoachContracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_code', models.IntegerField(null=True)),
                ('captcha_date', models.DateTimeField()),
                ('captcha_img', models.TextField()),
            ],
        ),
    ]
