# Generated by Django 4.2.2 on 2023-10-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoachContracts', '0002_captcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='coach_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_phone_number', models.IntegerField(unique=True)),
                ('coach_fullname', models.CharField(max_length=100)),
                ('coach_sharecode', models.CharField(max_length=100)),
                ('coach_city', models.CharField(max_length=50)),
                ('coach_experience', models.IntegerField()),
                ('coach_specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoachContracts.expertise')),
            ],
        ),
    ]
