# Generated by Django 4.2.2 on 2023-10-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoachContracts', '0002_coach_requests_coach_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach_requests',
            name='coach_sharecode',
        ),
    ]
