# Generated by Django 4.2.2 on 2023-10-19 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoachContracts', '0003_coach_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach_requests',
            name='coach_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coach_requests',
            name='coach_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coach_requests',
            name='coach_fullname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coach_requests',
            name='coach_sharecode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coach_requests',
            name='coach_specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CoachContracts.expertise'),
        ),
    ]
